name: Moni
 
on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'masukin CRD codenya'
        required: true
      pincode:
        description: 'Buat pin 6 digit'
        required: true
 
jobs:
  build:
    runs-on: windows-2019
 
    steps:
    - uses: actions/checkout@v3
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      uses: mxschmitt/action-tmate@v3
